dist: bionic
language: python

python:
  - "3.6"

install:
  - sudo apt-get install -y gmt gmt-dcw gmt-gshhg python3-tk libgirepository1.0-dev
  - pip3 install -r requirements.txt

stages:
  - compile
  - pep8check
  - pylintcheck
  - dockerbuild

jobs:
  include:
    - stage: compile
      script:
        - python3 -m compileall .
    - stage: pep8check
      before_install:
        - pip3 install pycodestyle
      script:
        - pycodestyle *.py || true
    - stage: pylintcheck
      before_install:
        - pip3 install pylint
      script:
        - pylint --exit-zero *.py
    - stage: dockerbuild
      install: skip
      script:
        - docker build -f metadata/Dockerfile . -t shakyground:test
        - docker run shakyground:test "/bin/bash" "run_and_validate.sh"
